---

- name: check if cluster was initialised 
  shell: kubectl --kubeconfig /etc/kubernetes/admin.conf cluster-info
  ignore_errors: yes
  changed_when: false
  register: cluster_status

- name: Initialise the Master Node
  shell: kubeadm init
  when: cluster_status.rc != 0

- name: Register Token
  shell: kubeadm token list | tail -n 1 | awk '{ print $1 }'
  register: token

- name: Register Discovery Token
  shell: openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | \
   openssl dgst -sha256 -hex | sed 's/^.* //'
  register: discovery_token

- name: put token in Vhost
  add_host:
    name: "tokenhost"
    token: "{{ token.stdout }}"
    discovery_token: "{{ discovery_token.stdout  }}"
    ip: "{{ ansible_default_ipv4.address }}"

- name: Set KUBECONFIG env
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^KUBECONFIG'
    line: 'KUBECONFIG=/etc/kubernetes/admin.conf'

- name: Register Calico CNI Plugin
  ansible.builtin.get_url:
    url: https://docs.projectcalico.org/manifests/calico.yaml
    dest: /root/calico.yaml

- name: Check Calico was not installed
  shell: kubectl get pod --all-namespaces | grep calico | wc -l
  ignore_errors: yes
  changed_when: false
  register: calico

- name: Install Calico Network
  shell: kubectl apply -f /root/calico.yaml
  when: calico.stdout == "0"
