---

- name: dnf repos update
  ansible.builtin.copy:
    src: rocky_repos/
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: '0644'

- name: Set selinux in permissive mode
  shell: setenforce 0 && sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
