---
# tasks file for kube_inst

- include_tasks: requirements_centos.yml
  when: ansible_facts['distribution'] == 'CentOS'

- include_tasks: requirements_ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- include_tasks: master_node.yml
  when: inventory_hostname in groups['masternode']

- include_tasks: workers.yml
  when: inventory_hostname in groups['workers']
