---
# tasks file for kube_inst

- include_tasks: requirements_rocky.yml
  when: ansible_facts['distribution'] == 'Rocky'

- include_tasks: requirements_ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- include_tasks: master_node.yml
  when: inventory_hostname in groups['masternode']

  #- include_tasks: workers.yml
  # when: inventory_hostname in groups['workers']
