---

- name: load kernel parameters at startup
  ansible.builtin.copy:
    src: k8s.conf
    dest: /etc/sysctl.d/

- name: let iptables see bridged traffic
  modprobe:
    name: br_netfilter
    state: present

- name: authorize ipv4 forwarding
  ansible.builtin.shell: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: Initialise the Master Node
  ansible.builtin.shell:
    cmd: kubeadm init
