---

- name: load kernel parameters at startup
  ansible.builtin.copy:
    src: k8s.conf
    dest: /etc/sysctl.d/

- name: let iptables see bridged traffic
  modprobe:
    name: br_netfilter
    state: present

- name: authorize ipv4 forwarding
  shell: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: restart docker
  ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: true

- name: restart kubelet
  ansible.builtin.service:
    name: kubelet
    state: stopped
    enabled: true

- name: Initialise the Master Node
  shell: kubeadm init 
