---

- name: dnf repos update
  ansible.builtin.copy:
    src: centos_repos/
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: '0644'

- name: Set selinux in permissive mode
  ansible.builtin.shell: setenforce 0 && sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

- name: Install Packages containerd, kubelet,kubeadm,kubectl
  ansible.builtin.package:
    name:
      - containerd
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes
  notify:
  - start containerd
