---

- name: Apt repos update
  ansible.builtin.copy:
    src: ubuntu_repos/
    dest: /etc/apt/sources.list.d/
    owner: root
    group: root
    mode: '0644'

- name: convert Gpg Key
  ansible.builtin.shell: 
    cmd: if [ ! -f /usr/share/keyrings/docker.gpg ]; then curl -fssl https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker.gpg; fi
    warn: yes
    executable: /bin/bash

- name: Download Google Cloud Public signing key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Install kubelet, kubeadm and kubectl
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes
