---

- name: Apt repos update
  ansible.builtin.copy:
    src: ubuntu_repos/
    dest: /etc/apt/sources.list.d/
    owner: root
    group: root
    mode: '0644'


- name: convert Gpg Key
  shell: if [ ! -f /usr/share/keyrings/docker.gpg ]; then curl -fssl https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker.gpg; fi


- name: Download Google Cloud Public signing key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg


- name: Install Packages docker,kubelet,kubeadm,kubectl
  ansible.builtin.package:
    name:
      - containerd
      - kubelet
      - kubeadm
      - kubectl
      - haproxy
      - keepalived
    state: present
    update_cache: yes

- name : Start Services Containerd
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: yes 

- name : Start Services Kubelet
  ansible.builtin.service:
    name: kubelet
    state: stopped
    enabled: yes 
